language: node_js
node_js:
- 6
- 8
deploy:
  provider: npm
  email: aws@foko.co
  api_key:
    secure: Oi0ZsVfK3F2IBwWGG9iq9D0BqkrgAE5vgctLtDcF3NwovPpamJzWuzTEYdv5Ke1QT/dYDpuvglJ2ruwVbtcjQqNMBvXGyhofgK4t3A3cXrQ1eDAOFrb7tQGt5J1K3vz+TMKu5KkblWstPc+jtdXlGfIUj8/fFsva8PEbI+kwLj6vI4LO8/e3W1ZHbq5jCoY5vT1lcV56HpPP1FE+rAiJR6eMGcpeW2M/a/zFxqQ8HFhqUrhxZ1sB4VV1LqCrhqNgF0mIeO47QCeUSAwqkOh73B862VVfYoVT9ON9pKwmwqnI3c44/tbe45obUl4hveVAr8wwErTVRYYcl9jNJkrLIwbBf4425dVepVPocL80vDXew3+lrg7WxkU08Io6Lz3ZGF/u/ot7qeks8qhyQz9pkV2WNDnqx//EoRfobPSwXeHypJdzGfZ/abBNN+IGj3/Y4+loFJLQjRuQSLZh3TfshYPtON57XpYMcMmXpfhKn7Ak0lUYNnVSC9UngnS+q7rob3IIWTxK5ysQQY5dnGsMV4GeUKBQmaCiluz8v5GAkncdY0/2Ua4qH1l4Oy1F9vbbhjT1ecJgf1YF+FZgWVFf7D/Uc/j+ARPVUCXU7eIcgsy2QYaxkf7h9+Zw7upcJuxDD/3j7xVTeQoaumItNhuemvqtOtf8lB9x1fUzeVnQREg=
  on:
    tags: true
    repo: FoKo/js-xlsx
